/*  MAIN ACTIONS   */
export const FIRST_TIME_LOGIN = 'FIRST_TIME_LOGIN';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const GET_USER_AGENT = 'GET_USER_AGENT';
export const TRIGGER_SAVINGS_PAGE = 'TRIGGER_SAVINGS_PAGE';
export const GET_USER_AVATAR_SOURCE = 'GET_USER_AVATAR_SOURCE';
export const GET_CAPTURED_IMAGE_URI = 'GET_CAPTURED_IMAGE_URI';

export const CHANGE_SELECTED_TO_DELETE_COUNT =
  'CHANGE_SELECTED_TO_DELETE_COUNT';
export const CLEAR_SELECTED_TO_DELETE_COUNT = 'CLEAR_SELECTED_TO_DELETE_COUNT';

export const ADD_TO_DELETE_LIST = 'ADD_TO_DELETE_LIST';
export const REMOVE_FROM_DELETE_LIST = 'REMOVE_FROM_DELETE_LIST';
export const CLEAR_DELETE_LIST = 'CLEAR_DELETE_LIST';

export const GET_DETECTED_FACE_COUNT = 'GET_DETECTED_FACE_COUNT';

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER";

export const GET_USER_DATA = "GET_USER_DATA";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
